export const LATEX_CATEGORIES = [
  { id: 'all', name: 'Tất Cả' },
  { id: 'algebra', name: 'Đại Số & Lũy Thừa' },
  { id: 'geometry', name: 'Hình Học & Vectơ' },
  { id: 'equations', name: 'Hệ PT & Ngoặc' },
  { id: 'symbols', name: 'BĐT & Tập Hợp' },
  { id: 'calculus', name: 'Giải Tích & Tích Phân' },
  { id: 'greek', name: 'Ký Tự Hy Lạp' }
];

export const LATEX_FORMULAS = [
  // 1. Đại số & Lũy thừa (algebra)
  { id: 'frac', name: 'Phân số', cat: 'algebra', catName: 'Đại số', code: '\\frac{a}{b}', preview: '\\frac{a}{b}', desc: 'Phân số a trên b' },
  { id: 'pow', name: 'Lũy thừa / Số mũ', cat: 'algebra', catName: 'Đại số', code: 'x^{n}', preview: 'x^{n}', desc: 'x mũ n' },
  { id: 'sub', name: 'Chỉ số dưới', cat: 'algebra', catName: 'Đại số', code: 'x_{i}', preview: 'x_{i}', desc: 'x chỉ số i' },
  { id: 'subpow', name: 'Chỉ số & Số mũ', cat: 'algebra', catName: 'Đại số', code: 'x_{1}^{2}', preview: 'x_{1}^{2}', desc: 'x một bình phương' },
  { id: 'sqrt', name: 'Căn bậc hai', cat: 'algebra', catName: 'Đại số', code: '\\sqrt{x}', preview: '\\sqrt{x}', desc: 'Căn bậc hai của x' },
  { id: 'nroot', name: 'Căn bậc n', cat: 'algebra', catName: 'Đại số', code: '\\sqrt[n]{x}', preview: '\\sqrt[n]{x}', desc: 'Căn bậc n của x' },
  { id: 'abs', name: 'Giá trị tuyệt đối', cat: 'algebra', catName: 'Đại số', code: '|x|', preview: '|x|', desc: 'Trị tuyệt đối của x' },
  { id: 'cdot', name: 'Phép nhân chấm', cat: 'algebra', catName: 'Đại số', code: 'a \\cdot b', preview: 'a \\cdot b', desc: 'Dấu chấm nhân' },
  { id: 'times', name: 'Phép nhân chéo', cat: 'algebra', catName: 'Đại số', code: 'a \\times b', preview: 'a \\times b', desc: 'Dấu nhân chữ x' },
  { id: 'div', name: 'Phép chia', cat: 'algebra', catName: 'Đại số', code: 'a \\div b', preview: 'a \\div b', desc: 'Dấu chia hai chấm' },
  { id: 'pm', name: 'Cộng trừ', cat: 'algebra', catName: 'Đại số', code: '\\pm x', preview: '\\pm x', desc: 'Dấu cộng trừ' },
  { id: 'mp', name: 'Trừ cộng', cat: 'algebra', catName: 'Đại số', code: '\\mp x', preview: '\\mp x', desc: 'Dấu trừ cộng' },
  { id: 'fact', name: 'Giai thừa', cat: 'algebra', catName: 'Đại số', code: 'n!', preview: 'n!', desc: 'n giai thừa' },
  { id: 'binom', name: 'Tổ hợp / Nhị thức', cat: 'algebra', catName: 'Đại số', code: '\\binom{n}{k}', preview: '\\binom{n}{k}', desc: 'Tổ hợp chập k của n' },
  { id: 'pmod', name: 'Đồng dư thức', cat: 'algebra', catName: 'Đại số', code: 'a \\equiv b \\pmod{m}', preview: 'a \\equiv b \\pmod{m}', desc: 'a đồng dư b mod m' },

  // 2. Hình học & Vectơ (geometry)
  { id: 'triangle', name: 'Tam giác', cat: 'geometry', catName: 'Hình học', code: '\\triangle ABC', preview: '\\triangle ABC', desc: 'Tam giác ABC' },
  { id: 'angle_hat', name: 'Góc mũ đỉnh', cat: 'geometry', catName: 'Hình học', code: '\\widehat{A}', preview: '\\widehat{A}', desc: 'Góc A với dấu mũ' },
  { id: 'angle_full', name: 'Góc 3 đỉnh', cat: 'geometry', catName: 'Hình học', code: '\\widehat{ABC}', preview: '\\widehat{ABC}', desc: 'Góc ABC' },
  { id: 'angle_symbol', name: 'Ký hiệu góc', cat: 'geometry', catName: 'Hình học', code: '\\angle ABC', preview: '\\angle ABC', desc: 'Ký hiệu góc ABC' },
  { id: 'vector_u', name: 'Vectơ đơn', cat: 'geometry', catName: 'Hình học', code: '\\vec{u}', preview: '\\vec{u}', desc: 'Vectơ u' },
  { id: 'vector_ab', name: 'Vectơ đoạn thẳng', cat: 'geometry', catName: 'Hình học', code: '\\vec{AB}', preview: '\\vec{AB}', desc: 'Vectơ AB có hướng' },
  { id: 'vector_len', name: 'Độ dài vectơ', cat: 'geometry', catName: 'Hình học', code: '|\\vec{AB}|', preview: '|\\vec{AB}|', desc: 'Độ dài vectơ AB' },
  { id: 'perp', name: 'Vuông góc', cat: 'geometry', catName: 'Hình học', code: 'd_1 \\perp d_2', preview: 'd_1 \\perp d_2', desc: 'Hai đường thẳng vuông góc' },
  { id: 'parallel', name: 'Song song', cat: 'geometry', catName: 'Hình học', code: 'AB \\parallel CD', preview: 'AB \\parallel CD', desc: 'Hai đường thẳng song song' },
  { id: 'sim', name: 'Đồng dạng', cat: 'geometry', catName: 'Hình học', code: '\\triangle ABC \\sim \\triangle A\'B\'C\'', preview: '\\triangle ABC \\sim \\triangle A\'B\'C\'', desc: 'Hai tam giác đồng dạng' },
  { id: 'cong', name: 'Bằng nhau hình học', cat: 'geometry', catName: 'Hình học', code: '\\triangle ABC \\cong \\triangle DEF', preview: '\\triangle ABC \\cong \\triangle DEF', desc: 'Hai tam giác bằng nhau' },
  { id: 'degree', name: 'Độ (góc)', cat: 'geometry', catName: 'Hình học', code: '90^\\circ', preview: '90^\\circ', desc: '90 độ' },
  { id: 'circle', name: 'Đường tròn', cat: 'geometry', catName: 'Hình học', code: '(O; R)', preview: '(O; R)', desc: 'Đường tròn tâm O bán kính R' },

  // 3. Hệ Phương Trình & Ngoặc (equations)
  { id: 'cases2', name: 'Hệ 2 phương trình', cat: 'equations', catName: 'Hệ PT', code: '\\begin{cases} x + y = 1 \\\\ x - y = 0 \\end{cases}', preview: '\\begin{cases} x + y = 1 \\\\ x - y = 0 \\end{cases}', desc: 'Hệ 2 phương trình 2 ẩn' },
  { id: 'cases3', name: 'Hệ 3 phương trình', cat: 'equations', catName: 'Hệ PT', code: '\\begin{cases} x + y + z = 6 \\\\ 2x - y + z = 3 \\\\ x + 2y - z = 2 \\end{cases}', preview: '\\begin{cases} x + y + z = 6 \\\\ 2x - y + z = 3 \\\\ x + 2y - z = 2 \\end{cases}', desc: 'Hệ 3 phương trình 3 ẩn' },
  { id: 'cases_or', name: 'Tuyển nghiệm (hoặc)', cat: 'equations', catName: 'Hệ PT', code: '\\left[ \\begin{array}{l} x = 1 \\\\ x = -1 \\end{array} \\right.', preview: '\\left[ \\begin{array}{l} x = 1 \\\\ x = -1 \\end{array} \\right.', desc: 'Dấu ngoặc vuông hoặc' },
  { id: 'brackets_round', name: 'Ngoặc tròn co giãn', cat: 'equations', catName: 'Hệ PT', code: '\\left( \\frac{a}{b} \\right)', preview: '\\left( \\frac{a}{b} \\right)', desc: 'Ngoặc tròn tự điều chỉnh chiều cao' },
  { id: 'brackets_square', name: 'Ngoặc vuông co giãn', cat: 'equations', catName: 'Hệ PT', code: '\\left[ \\frac{a}{b} \\right]', preview: '\\left[ \\frac{a}{b} \\right]', desc: 'Ngoặc vuông tự co giãn' },
  { id: 'brackets_curly', name: 'Ngoặc nhọn co giãn', cat: 'equations', catName: 'Hệ PT', code: '\\left\\{ \\frac{a}{b} \\right\\}', preview: '\\left\\{ \\frac{a}{b} \\right\\}', desc: 'Ngoặc nhọn tự co giãn' },
  { id: 'matrix2', name: 'Ma trận 2x2', cat: 'equations', catName: 'Hệ PT', code: '\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}', preview: '\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}', desc: 'Ma trận ngoặc tròn' },
  { id: 'det2', name: 'Định thức 2x2', cat: 'equations', catName: 'Hệ PT', code: '\\begin{vmatrix} a & b \\\\ c & d \\end{vmatrix}', preview: '\\begin{vmatrix} a & b \\\\ c & d \\end{vmatrix}', desc: 'Định thức hai vạch thẳng' },

  // 4. Bất Đẳng Thức & Tập Hợp (symbols)
  { id: 'le', name: 'Nhỏ hơn hoặc bằng', cat: 'symbols', catName: 'BĐT & Ký hiệu', code: '\\le', preview: 'a \\le b', desc: 'Ký hiệu nhỏ hơn hoặc bằng' },
  { id: 'ge', name: 'Lớn hơn hoặc bằng', cat: 'symbols', catName: 'BĐT & Ký hiệu', code: '\\ge', preview: 'a \\ge b', desc: 'Ký hiệu lớn hơn hoặc bằng' },
  { id: 'neq', name: 'Khác', cat: 'symbols', catName: 'BĐT & Ký hiệu', code: '\\neq', preview: 'a \\neq b', desc: 'Dấu khác' },
  { id: 'approx', name: 'Xấp xỉ', cat: 'symbols', catName: 'BĐT & Ký hiệu', code: '\\approx', preview: 'a \\approx b', desc: 'Dấu xấp xỉ gần bằng' },
  { id: 'implies', name: 'Suy ra (kéo theo)', cat: 'symbols', catName: 'BĐT & Ký hiệu', code: '\\Rightarrow', preview: 'P \\Rightarrow Q', desc: 'Mệnh đề suy ra' },
  { id: 'iff', name: 'Tương đương', cat: 'symbols', catName: 'BĐT & Ký hiệu', code: '\\Leftrightarrow', preview: 'P \\Leftrightarrow Q', desc: 'Mệnh đề tương đương' },
  { id: 'forall', name: 'Với mọi', cat: 'symbols', catName: 'BĐT & Ký hiệu', code: '\\forall x', preview: '\\forall x \\in \\mathbb{R}', desc: 'Lượng từ với mọi' },
  { id: 'exists', name: 'Tồn tại', cat: 'symbols', catName: 'BĐT & Ký hiệu', code: '\\exists x', preview: '\\exists x > 0', desc: 'Lượng từ tồn tại' },
  { id: 'in', name: 'Thuộc tập hợp', cat: 'symbols', catName: 'BĐT & Ký hiệu', code: 'x \\in A', preview: 'x \\in A', desc: 'Phần tử thuộc tập hợp' },
  { id: 'notin', name: 'Không thuộc tập hợp', cat: 'symbols', catName: 'BĐT & Ký hiệu', code: 'x \\notin A', preview: 'x \\notin A', desc: 'Phần tử không thuộc' },
  { id: 'subset', name: 'Tập hợp con', cat: 'symbols', catName: 'BĐT & Ký hiệu', code: 'A \\subset B', preview: 'A \\subset B', desc: 'A là tập con của B' },
  { id: 'union', name: 'Hợp tập hợp', cat: 'symbols', catName: 'BĐT & Ký hiệu', code: 'A \\cup B', preview: 'A \\cup B', desc: 'Phép hợp 2 tập hợp' },
  { id: 'cap', name: 'Giao tập hợp', cat: 'symbols', catName: 'BĐT & Ký hiệu', code: 'A \\cap B', preview: 'A \\cap B', desc: 'Phép giao 2 tập hợp' },
  { id: 'empty', name: 'Tập hợp rỗng', cat: 'symbols', catName: 'BĐT & Ký hiệu', code: '\\emptyset', preview: '\\emptyset', desc: 'Tập rỗng' },
  { id: 'set_r', name: 'Tập số thực R', cat: 'symbols', catName: 'BĐT & Ký hiệu', code: '\\mathbb{R}', preview: '\\mathbb{R}', desc: 'Tập hợp số thực' },
  { id: 'set_n', name: 'Tập số tự nhiên N', cat: 'symbols', catName: 'BĐT & Ký hiệu', code: '\\mathbb{N}', preview: '\\mathbb{N}', desc: 'Tập số tự nhiên' },
  { id: 'set_z', name: 'Tập số nguyên Z', cat: 'symbols', catName: 'BĐT & Ký hiệu', code: '\\mathbb{Z}', preview: '\\mathbb{Z}', desc: 'Tập số nguyên' },
  { id: 'set_q', name: 'Tập số hữu tỉ Q', cat: 'symbols', catName: 'BĐT & Ký hiệu', code: '\\mathbb{Q}', preview: '\\mathbb{Q}', desc: 'Tập số hữu tỉ' },

  // 5. Giải Tích & Tích Phân (calculus)
  { id: 'sum', name: 'Tổng Sigma', cat: 'calculus', catName: 'Giải tích', code: '\\sum_{i=1}^{n} a_i', preview: '\\sum_{i=1}^{n} a_i', desc: 'Tổng từ i=1 đến n' },
  { id: 'prod', name: 'Tích Pi', cat: 'calculus', catName: 'Giải tích', code: '\\prod_{i=1}^{n} a_i', preview: '\\prod_{i=1}^{n} a_i', desc: 'Tích từ i=1 đến n' },
  { id: 'lim', name: 'Giới hạn', cat: 'calculus', catName: 'Giải tích', code: '\\lim_{x \\to 0} f(x)', preview: '\\lim_{x \\to 0} f(x)', desc: 'Giới hạn khi x tiến đến 0' },
  { id: 'infty', name: 'Vô cực / Vô cùng', cat: 'calculus', catName: 'Giải tích', code: '\\infty', preview: '+\\infty', desc: 'Dấu vô cực' },
  { id: 'int_def', name: 'Tích phân xác định', cat: 'calculus', catName: 'Giải tích', code: '\\int_{a}^{b} f(x)dx', preview: '\\int_{a}^{b} f(x)dx', desc: 'Tích phân từ a đến b' },
  { id: 'int_indef', name: 'Tích phân bất định', cat: 'calculus', catName: 'Giải tích', code: '\\int f(x)dx', preview: '\\int f(x)dx', desc: 'Nguyên hàm của f(x)' },
  { id: 'derivative', name: 'Đạo hàm', cat: 'calculus', catName: 'Giải tích', code: 'f\'(x)', preview: 'f\'(x)', desc: 'f phẩy x' },
  { id: 'partial', name: 'Đạo hàm riêng', cat: 'calculus', catName: 'Giải tích', code: '\\frac{\\partial f}{\\partial x}', preview: '\\frac{\\partial f}{\\partial x}', desc: 'Đạo hàm riêng của f theo x' },

  // 6. Ký Tự Hy Lạp (greek)
  { id: 'pi', name: 'Số Pi', cat: 'greek', catName: 'Hy Lạp', code: '\\pi', preview: '\\pi', desc: 'Số Pi ≈ 3.14159' },
  { id: 'alpha', name: 'Alpha', cat: 'greek', catName: 'Hy Lạp', code: '\\alpha', preview: '\\alpha', desc: 'Chữ cái Hy Lạp alpha' },
  { id: 'beta', name: 'Beta', cat: 'greek', catName: 'Hy Lạp', code: '\\beta', preview: '\\beta', desc: 'Chữ cái Hy Lạp beta' },
  { id: 'gamma', name: 'Gamma', cat: 'greek', catName: 'Hy Lạp', code: '\\gamma', preview: '\\gamma', desc: 'Chữ cái Hy Lạp gamma' },
  { id: 'delta_lower', name: 'Delta thường', cat: 'greek', catName: 'Hy Lạp', code: '\\delta', preview: '\\delta', desc: 'Delta thường' },
  { id: 'delta_upper', name: 'Delta hoa (biệt thức)', cat: 'greek', catName: 'Hy Lạp', code: '\\Delta', preview: '\\Delta', desc: 'Delta hoa / tam giác biệt thức' },
  { id: 'theta', name: 'Theta (góc)', cat: 'greek', catName: 'Hy Lạp', code: '\\theta', preview: '\\theta', desc: 'Theta góc lượng giác' },
  { id: 'lambda', name: 'Lambda', cat: 'greek', catName: 'Hy Lạp', code: '\\lambda', preview: '\\lambda', desc: 'Lambda' },
  { id: 'sigma_lower', name: 'Sigma thường', cat: 'greek', catName: 'Hy Lạp', code: '\\sigma', preview: '\\sigma', desc: 'Sigma thường' },
  { id: 'omega', name: 'Omega', cat: 'greek', catName: 'Hy Lạp', code: '\\omega', preview: '\\omega', desc: 'Omega' },
  { id: 'phi', name: 'Phi (tỉ lệ vàng)', cat: 'greek', catName: 'Hy Lạp', code: '\\phi', preview: '\\phi', desc: 'Ký hiệu Phi' },
  { id: 'dots_h', name: 'Dấu ba chấm ngang', cat: 'greek', catName: 'Hy Lạp', code: '\\dots', preview: '1, 2, \\dots, n', desc: 'Ba chấm ngang' },
  { id: 'dots_v', name: 'Dấu ba chấm dọc', cat: 'greek', catName: 'Hy Lạp', code: '\\vdots', preview: '\\vdots', desc: 'Ba chấm dọc cho ma trận' },
  { id: 'dots_d', name: 'Dấu ba chấm chéo', cat: 'greek', catName: 'Hy Lạp', code: '\\ddots', preview: '\\ddots', desc: 'Ba chấm chéo cho ma trận' }
];
