// Danh sách 34 Tỉnh / Thành phố sau sáp nhập (theo Nghị quyết 202/2025/QH15 của Quốc hội)
export const PROVINCES_34 = [
  { name: "An Giang", mergedFrom: "An Giang, Kiên Giang" },
  { name: "Bắc Ninh", mergedFrom: "Bắc Ninh, Bắc Giang" },
  { name: "Cà Mau", mergedFrom: "Cà Mau, Bạc Liêu" },
  { name: "Cao Bằng", mergedFrom: "" },
  { name: "Cần Thơ", mergedFrom: "Cần Thơ, Sóc Trăng, Hậu Giang" },
  { name: "Đà Nẵng", mergedFrom: "Đà Nẵng, Quảng Nam" },
  { name: "Đắk Lắk", mergedFrom: "Đắk Lắk, Phú Yên" },
  { name: "Điện Biên", mergedFrom: "" },
  { name: "Đồng Nai", mergedFrom: "Đồng Nai, Bình Phước" },
  { name: "Đồng Tháp", mergedFrom: "Đồng Tháp, Tiền Giang" },
  { name: "Gia Lai", mergedFrom: "Gia Lai, Bình Định" },
  { name: "Hà Nội", mergedFrom: "" },
  { name: "Hà Tĩnh", mergedFrom: "" },
  { name: "Hải Phòng", mergedFrom: "Hải Phòng, Hải Dương" },
  { name: "Huế", mergedFrom: "" },
  { name: "Hưng Yên", mergedFrom: "Hưng Yên, Thái Bình" },
  { name: "Khánh Hòa", mergedFrom: "Khánh Hòa, Ninh Thuận" },
  { name: "Lai Châu", mergedFrom: "" },
  { name: "Lâm Đồng", mergedFrom: "Lâm Đồng, Đắk Nông, Bình Thuận" },
  { name: "Lạng Sơn", mergedFrom: "" },
  { name: "Lào Cai", mergedFrom: "Lào Cai, Yên Bái" },
  { name: "Nghệ An", mergedFrom: "" },
  { name: "Ninh Bình", mergedFrom: "Ninh Bình, Hà Nam, Nam Định" },
  { name: "Phú Thọ", mergedFrom: "Phú Thọ, Vĩnh Phúc, Hòa Bình" },
  { name: "Quảng Ngãi", mergedFrom: "Quảng Ngãi, Kon Tum" },
  { name: "Quảng Ninh", mergedFrom: "" },
  { name: "Quảng Trị", mergedFrom: "Quảng Trị, Quảng Bình" },
  { name: "Sơn La", mergedFrom: "" },
  { name: "Tây Ninh", mergedFrom: "Tây Ninh, Long An" },
  { name: "Thái Nguyên", mergedFrom: "Thái Nguyên, Bắc Kạn" },
  { name: "Thanh Hóa", mergedFrom: "" },
  { name: "TP. Hồ Chí Minh", mergedFrom: "TP. Hồ Chí Minh, Bình Dương, Bà Rịa - Vũng Tàu" },
  { name: "Tuyên Quang", mergedFrom: "Tuyên Quang, Hà Giang" },
  { name: "Vĩnh Long", mergedFrom: "Vĩnh Long, Bến Tre, Trà Vinh" }
];
